# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_pages', '0003_auto_20170504_0706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['position', 'title']},
        ),
        migrations.AddField(
            model_name='page',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
