# Generated by Django 4.2.16 on 2024-12-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretix_pages", "0004_auto_20170517_1550"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="content_type",
            field=models.CharField(default="html", max_length=10),
        ),
    ]
